# Generated by Django 2.2.19 on 2022-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220602_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
    ]
