# Generated by Django 2.2.19 on 2022-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_new_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
