# Generated by Django 2.2.6 on 2022-06-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220609_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_post',
        ),
    ]
